// <auto-generated />
using System;
using LS.Persistence.Features.Accounting.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LS.Persistence.Migrations.AccountingPostgreSqlDB
{
    [DbContext(typeof(AccountingPostgreSqlDBContext))]
    [Migration("20260909221215_AddAccountingDLQ")]
    partial class AddAccountingDLQ
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LS.Domain.Features.Accounting.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[0]);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AccountCode")
                        .IsUnique();

                    b.ToTable("Accounts", "accounting");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0194f700-1000-7000-8000-000000001000"),
                            AccountCode = "1000",
                            AccountName = "Cash in Hand",
                            AccountType = "Asset",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Physical cash at branches",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-1000-7000-8000-000000001010"),
                            AccountCode = "1010",
                            AccountName = "Bank Account (Operating)",
                            AccountType = "Asset",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Main operating bank account",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-1000-7000-8000-000000001020"),
                            AccountCode = "1020",
                            AccountName = "Mobile Money Account (M-Pesa)",
                            AccountType = "Asset",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "M-Pesa Paybill / Till",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-1000-7000-8000-000000001100"),
                            AccountCode = "1100",
                            AccountName = "Normal Loans to Members",
                            AccountType = "Asset",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Outstanding principal for normal loans",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-1000-7000-8000-000000001110"),
                            AccountCode = "1110",
                            AccountName = "Emergency Loans to Members",
                            AccountType = "Asset",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Outstanding principal for emergency loans",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-1000-7000-8000-000000001120"),
                            AccountCode = "1120",
                            AccountName = "School Fee Loans to Members",
                            AccountType = "Asset",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Outstanding principal for school fee loans",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-1000-7000-8000-000000001130"),
                            AccountCode = "1130",
                            AccountName = "Asset Finance Loans to Members",
                            AccountType = "Asset",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Outstanding principal for asset finance",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-1000-7000-8000-000000001200"),
                            AccountCode = "1200",
                            AccountName = "Interest Receivable from Loans",
                            AccountType = "Asset",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Accrued interest not yet paid",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-1000-7000-8000-000000001300"),
                            AccountCode = "1300",
                            AccountName = "Accounts Receivable",
                            AccountType = "Asset",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Other receivables",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-1000-7000-8000-000000001400"),
                            AccountCode = "1400",
                            AccountName = "Property, Plant & Equipment",
                            AccountType = "Asset",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Fixed assets",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-1000-7000-8000-000000001410"),
                            AccountCode = "1410",
                            AccountName = "Intangible Assets",
                            AccountType = "Asset",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Software licenses, etc.",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-2000-7000-8000-000000002000"),
                            AccountCode = "2000",
                            AccountName = "Member Deposits (BOSA)",
                            AccountType = "Liability",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Non-withdrawable member deposits used as multiplier",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-2000-7000-8000-000000002010"),
                            AccountCode = "2010",
                            AccountName = "Member Savings (FOSA)",
                            AccountType = "Liability",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Withdrawable ordinary savings",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-2000-7000-8000-000000002020"),
                            AccountCode = "2020",
                            AccountName = "Fixed Deposits",
                            AccountType = "Liability",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Term deposits from members",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-2000-7000-8000-000000002100"),
                            AccountCode = "2100",
                            AccountName = "Accounts Payable",
                            AccountType = "Liability",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Trade creditors",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-2000-7000-8000-000000002200"),
                            AccountCode = "2200",
                            AccountName = "Unallocated Funds",
                            AccountType = "Liability",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Suspense account for unverified receipts",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-2000-7000-8000-000000002300"),
                            AccountCode = "2300",
                            AccountName = "Statutory Deductions Payable",
                            AccountType = "Liability",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "PAYE, NSSF, SHIF liabilities",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-2000-7000-8000-000000002400"),
                            AccountCode = "2400",
                            AccountName = "Dividends Payable",
                            AccountType = "Liability",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Declared but unpaid dividends",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-2000-7000-8000-000000002500"),
                            AccountCode = "2500",
                            AccountName = "External Borrowings",
                            AccountType = "Liability",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Bank loans to the Sacco",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-3000-7000-8000-000000003000"),
                            AccountCode = "3000",
                            AccountName = "Share Capital",
                            AccountType = "Equity",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Core capital contribution per member",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-3000-7000-8000-000000003100"),
                            AccountCode = "3100",
                            AccountName = "Retained Earnings",
                            AccountType = "Equity",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Accumulated surpluses",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-3000-7000-8000-000000003200"),
                            AccountCode = "3200",
                            AccountName = "Statutory Reserve Fund",
                            AccountType = "Equity",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "SASRA required 20% of surplus reserve",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-4000-7000-8000-000000004000"),
                            AccountCode = "4000",
                            AccountName = "Interest Income from Loans",
                            AccountType = "Revenue",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Main interest revenue",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-4000-7000-8000-000000004010"),
                            AccountCode = "4010",
                            AccountName = "Interest Income from Investments",
                            AccountType = "Revenue",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "T-Bills, interbank lending",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-4000-7000-8000-000000004100"),
                            AccountCode = "4100",
                            AccountName = "Fee and Commission Income",
                            AccountType = "Revenue",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "General fees",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-4000-7000-8000-000000004110"),
                            AccountCode = "4110",
                            AccountName = "Loan Application Fees",
                            AccountType = "Revenue",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Processing fees for loans",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-4000-7000-8000-000000004200"),
                            AccountCode = "4200",
                            AccountName = "Penalty Income",
                            AccountType = "Revenue",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Late payment penalties",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-4000-7000-8000-000000004300"),
                            AccountCode = "4300",
                            AccountName = "Other Operating Income",
                            AccountType = "Revenue",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Miscellaneous income",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-5000-7000-8000-000000005000"),
                            AccountCode = "5000",
                            AccountName = "Personnel Expenses",
                            AccountType = "Expense",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Staff salaries, wages, benefits",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-5000-7000-8000-000000005010"),
                            AccountCode = "5010",
                            AccountName = "Board & Committee Allowances",
                            AccountType = "Expense",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Governance costs",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-5000-7000-8000-000000005100"),
                            AccountCode = "5100",
                            AccountName = "Administrative Expenses",
                            AccountType = "Expense",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Rent, utilities, licenses, software",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-5000-7000-8000-000000005200"),
                            AccountCode = "5200",
                            AccountName = "Financial Expenses",
                            AccountType = "Expense",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Bank charges, interest on borrowing",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-5000-7000-8000-000000005300"),
                            AccountCode = "5300",
                            AccountName = "Provision for Bad Debts",
                            AccountType = "Expense",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Expected credit loss allowance",
                            IsActive = true,
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("LS.Domain.Features.Accounting.Entities.AccountingIntegrationError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[0]);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccountingIntegrationErrors");
                });

            modelBuilder.Entity("LS.Domain.Features.Accounting.Entities.Journal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[0]);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ReferenceNumber")
                        .IsUnique();

                    b.ToTable("Journals", "accounting");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0194f700-9000-7000-8000-000000009000"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Opening Balances Migration",
                            ReferenceNumber = "OB-001",
                            RowVersion = new byte[0],
                            Status = "Posted",
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001"),
                            TransactionDate = new DateTimeOffset(new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("LS.Domain.Features.Accounting.Entities.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CostCenterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Credit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Debit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[0]);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JournalId");

                    b.ToTable("JournalLines", "accounting");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0194f700-9000-7000-8000-000000009001"),
                            AccountId = new Guid("0194f700-1000-7000-8000-000000001010"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Credit = 0m,
                            Debit = 1000000m,
                            Description = "Opening Bank Balance",
                            JournalId = new Guid("0194f700-9000-7000-8000-000000009000"),
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-9000-7000-8000-000000009002"),
                            AccountId = new Guid("0194f700-3000-7000-8000-000000003000"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Credit = 500000m,
                            Debit = 0m,
                            Description = "Opening Share Capital",
                            JournalId = new Guid("0194f700-9000-7000-8000-000000009000"),
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f700-9000-7000-8000-000000009003"),
                            AccountId = new Guid("0194f700-3000-7000-8000-000000003100"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Credit = 500000m,
                            Debit = 0m,
                            Description = "Opening Retained Earnings",
                            JournalId = new Guid("0194f700-9000-7000-8000-000000009000"),
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("LS.Domain.Features.Accounting.Entities.TransactionTypeGlMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CreditExplicitGlAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreditSideSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("DebitExplicitGlAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("DebitSideSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("FeeExplicitGlAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("FeeSideSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[0]);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionTypeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreditExplicitGlAccountId");

                    b.HasIndex("DebitExplicitGlAccountId");

                    b.HasIndex("FeeExplicitGlAccountId");

                    b.HasIndex("TenantId", "TransactionTypeCode")
                        .IsUnique();

                    b.ToTable("TransactionTypeGlMappings", "accounting");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0194f700-6000-7000-8000-000000006001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            CreditSideSource = "CHANNEL_ACCOUNT",
                            DebitSideSource = "PRODUCT_ACCOUNT",
                            Description = "Loan Disbursement Mapping",
                            FeeExplicitGlAccountId = new Guid("0194f700-4000-7000-8000-000000004110"),
                            FeeSideSource = "EXPLICIT_GL",
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001"),
                            TransactionTypeCode = "LOAN_DISBURSEMENT"
                        },
                        new
                        {
                            Id = new Guid("0194f700-6000-7000-8000-000000006002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            CreditSideSource = "PRODUCT_ACCOUNT",
                            DebitSideSource = "CHANNEL_ACCOUNT",
                            Description = "Loan Repayment Mapping",
                            FeeExplicitGlAccountId = new Guid("0194f700-4000-7000-8000-000000004200"),
                            FeeSideSource = "EXPLICIT_GL",
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001"),
                            TransactionTypeCode = "LOAN_REPAYMENT"
                        },
                        new
                        {
                            Id = new Guid("0194f700-6000-7000-8000-000000006003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            CreditExplicitGlAccountId = new Guid("0194f700-3000-7000-8000-000000003000"),
                            CreditSideSource = "EXPLICIT_GL",
                            DebitSideSource = "CHANNEL_ACCOUNT",
                            Description = "Share Purchase Mapping",
                            FeeExplicitGlAccountId = new Guid("0194f700-4000-7000-8000-000000004100"),
                            FeeSideSource = "EXPLICIT_GL",
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001"),
                            TransactionTypeCode = "SHARE_PURCHASE"
                        },
                        new
                        {
                            Id = new Guid("0194f700-6000-7000-8000-000000006004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            CreditSideSource = "PRODUCT_ACCOUNT",
                            DebitSideSource = "CHANNEL_ACCOUNT",
                            Description = "Member Deposit Mapping",
                            FeeExplicitGlAccountId = new Guid("0194f700-4000-7000-8000-000000004100"),
                            FeeSideSource = "EXPLICIT_GL",
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001"),
                            TransactionTypeCode = "MEMBER_DEPOSIT"
                        });
                });

            modelBuilder.Entity("LS.Domain.Features.Accounting.Entities.JournalLine", b =>
                {
                    b.HasOne("LS.Domain.Features.Accounting.Entities.Account", "Account")
                        .WithMany("JournalLines")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LS.Domain.Features.Accounting.Entities.Journal", "Journal")
                        .WithMany("Lines")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("LS.Domain.Features.Accounting.Entities.TransactionTypeGlMapping", b =>
                {
                    b.HasOne("LS.Domain.Features.Accounting.Entities.Account", "CreditAccount")
                        .WithMany()
                        .HasForeignKey("CreditExplicitGlAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LS.Domain.Features.Accounting.Entities.Account", "DebitAccount")
                        .WithMany()
                        .HasForeignKey("DebitExplicitGlAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LS.Domain.Features.Accounting.Entities.Account", "FeeAccount")
                        .WithMany()
                        .HasForeignKey("FeeExplicitGlAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreditAccount");

                    b.Navigation("DebitAccount");

                    b.Navigation("FeeAccount");
                });

            modelBuilder.Entity("LS.Domain.Features.Accounting.Entities.Account", b =>
                {
                    b.Navigation("JournalLines");
                });

            modelBuilder.Entity("LS.Domain.Features.Accounting.Entities.Journal", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
