using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace LS.Tests.Architecture.Guardrails;

internal static class SourceArchitectureRules
{
    internal static readonly string[] RuleIds =
    ["UOW001", "UOW002", "UOW003", "UOW004", "DEP001", "VAL001", "LAY001", "LAY002", "ERR001", "CACHE001", "CACHE002"];

    internal static Dictionary<string, string> RepositorySources() =>
        new[] { "src", "tests" }.SelectMany(folder => Directory.EnumerateFiles(
                Path.Combine(AssemblyReferences.RepoRoot, folder), "*.cs", SearchOption.AllDirectories))
            .Where(IsAuthored).ToDictionary(p => Path.GetRelativePath(AssemblyReferences.RepoRoot, p).Replace('\\', '/'), File.ReadAllText);

    private static bool IsAuthored(string path)
    {
        var normalized = path.Replace('\\', '/');
        // Exclude generated artifacts, not whole feature/platform directories.
        return !normalized.Split('/').Any(part => part is "bin" or "obj") &&
            !normalized.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) &&
            !normalized.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase) &&
            !File.ReadLines(path).Take(5).Any(line => line.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase));
    }

    internal static IReadOnlyList<ArchitectureFinding> Analyze(IReadOnlyDictionary<string, string> sources)
    {
        var trees = sources.Select(s => CSharpSyntaxTree.ParseText(s.Value, path: s.Key)).ToArray();
        var globalUsings = CSharpSyntaxTree.ParseText("global using System; global using System.Collections.Generic; global using System.Linq; global using System.Threading; global using System.Threading.Tasks;");
        var references = ((string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!).Split(Path.PathSeparator)
            .Concat(Directory.EnumerateFiles(AppContext.BaseDirectory, "*.dll"))
            .GroupBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase).Select(g => MetadataReference.CreateFromFile(g.First()));
        var compilation = CSharpCompilation.Create("ArchitectureSourceInspection", trees.Append(globalUsings), references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        var findings = new List<ArchitectureFinding>();
        foreach (var tree in trees)
        {
            var model = compilation.GetSemanticModel(tree);
            var root = tree.GetRoot();
            var declarations = root.DescendantNodes().OfType<BaseTypeDeclarationSyntax>().ToArray();
            var topLevel = declarations.Where(d => d.Parent is BaseNamespaceDeclarationSyntax or CompilationUnitSyntax).ToArray();
            var publicTypes = topLevel.Where(d => d.Modifiers.Any(SyntaxKind.PublicKeyword)).ToArray();
            foreach (var declaration in declarations)
            {
                if (model.GetDeclaredSymbol(declaration) is not INamedTypeSymbol type) continue;
                var symbol = type.ToDisplayString();
                void Add(string rule, string detail, int phase, SyntaxNode? node = null, string? member = null) =>
                    findings.Add(new(rule, tree.FilePath, member ?? symbol,
                        (node ?? declaration).GetLocation().GetLineSpan().StartLinePosition.Line + 1, detail, phase));
                var isApplication = type.ContainingNamespace.ToDisplayString().StartsWith("LS.Application.Features.", StringComparison.Ordinal);
                var request = type.AllInterfaces.FirstOrDefault(i => Is(i, "MediatR", "IRequest"));
                var handler = type.AllInterfaces.FirstOrDefault(i => Is(i, "MediatR", "IRequestHandler"));
                if (type.TypeKind == TypeKind.Interface && type.Name.EndsWith("UnitOfWork", StringComparison.Ordinal))
                {
                    foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
                    {
                        if (property.Type is not INamedTypeSymbol propertyType) continue;
                        var raw = Is(propertyType, "LS.Domain.Shared.Contracts.Repositories", "IRepository");
                        var repository = raw || propertyType.Name.EndsWith("Repository", StringComparison.Ordinal) ||
                            propertyType.AllInterfaces.Any(i => Is(i, "LS.Domain.Shared.Contracts.Repositories", "IRepository"));
                        if (!repository) continue;
                        var node = property.DeclaringSyntaxReferences.First().GetSyntax();
                        if (!raw && (propertyType.TypeKind != TypeKind.Interface || !propertyType.AllInterfaces.Any(i => Is(i, "LS.Domain.Shared.Contracts.Repositories", "IRepository"))))
                            Add("UOW004", "Entity repository interface must inherit IRepository<TEntity>; specialized contracts require an exact reviewed exception", 3, node, property.ToDisplayString());
                        if (raw) Add("UOW001", "Expose a feature-specific repository interface instead of " + propertyType.ToDisplayString(), 3, node, property.ToDisplayString());
                        if (!property.Name.EndsWith("Repository", StringComparison.Ordinal))
                            Add("UOW002", "Repository properties must end in Repository", 3, node, property.ToDisplayString());
                    }
                }
                if (type.Name.EndsWith("UnitOfWork", StringComparison.Ordinal))
                {
                    foreach (var creation in declaration.DescendantNodes().OfType<BaseObjectCreationExpressionSyntax>())
                    {
                        if (model.GetTypeInfo(creation).Type is INamedTypeSymbol created && Is(created, "LS.Persistence.Common.Repositories", "Repository"))
                            Add("UOW003", "Inject a feature repository; do not construct " + created.ToDisplayString(), 3, creation,
                                symbol + "." + (creation.Ancestors().OfType<PropertyDeclarationSyntax>().FirstOrDefault()?.Identifier.ValueText ?? "constructor"));
                    }
                }
                if (handler is not null && isApplication)
                {
                    foreach (var parameter in type.InstanceConstructors.SelectMany(c => c.Parameters))
                    {
                        if (parameter.Type is INamedTypeSymbol dependency &&
                            (Is(dependency, "LS.Domain.Shared.Contracts.Repositories", "IRepository") ||
                             BaseTypes(dependency).Any(b => Is(b, "Microsoft.EntityFrameworkCore", "DbContext"))))
                            Add("DEP001", "Handler persistence must use a bounded-context Unit of Work", 3,
                                parameter.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax(), symbol + "." + parameter.Name);
                    }
                }
                if (BaseTypes(type).Any(b => Is(b, "FluentValidation", "AbstractValidator")) &&
                    (topLevel.Length != 1 || topLevel[0] != declaration || Path.GetFileNameWithoutExtension(tree.FilePath) != type.Name))
                    Add("VAL001", "Validator must occupy its own type-named file", 6);

                if (isApplication && request is not null && type.Name.EndsWith("Command", StringComparison.Ordinal))
                {
                    var operation = type.Name[..^"Command".Length];
                    var matchingHandlers = topLevel.Where(d => model.GetDeclaredSymbol(d) is INamedTypeSymbol candidate &&
                        candidate.DeclaredAccessibility == Accessibility.Internal && candidate.Name == type.Name + "Handler" &&
                        candidate.AllInterfaces.Any(i => Is(i, "MediatR", "IRequestHandler") &&
                            i.TypeArguments[0].ToDisplayString() == symbol)).ToArray();
                    if (Path.GetFileNameWithoutExtension(tree.FilePath) != operation || matchingHandlers.Length != 1 ||
                        topLevel.Length != 2 || !topLevel.Contains(declaration))
                        Add("LAY001", "Default: operation-named file containing only the command and its internal matching handler", 6);
                }
                if (publicTypes.Contains(declaration))
                {
                    var file = Path.GetFileNameWithoutExtension(tree.FilePath);
                    var ordinaryName = file == type.Name || (declaration.Modifiers.Any(SyntaxKind.PartialKeyword) && file.StartsWith(type.Name + ".", StringComparison.Ordinal));
                    var migrationName = BaseTypes(type).Any(b => Is(b, "Microsoft.EntityFrameworkCore.Migrations", "Migration")) &&
                        file.Length == 15 + type.Name.Length && file[..14].All(char.IsAsciiDigit) && file[14] == '_' && file[15..] == type.Name;
                    var operationPair = isApplication && request is not null && type.Name.EndsWith("Command", StringComparison.Ordinal) &&
                        file == type.Name[..^"Command".Length] && topLevel.Length == 2 && publicTypes.Length == 1 &&
                        topLevel.Any(d => model.GetDeclaredSymbol(d) is INamedTypeSymbol h && h.Name == type.Name + "Handler" &&
                            h.DeclaredAccessibility == Accessibility.Internal && h.AllInterfaces.Any(i => Is(i, "MediatR", "IRequestHandler") && i.TypeArguments[0].ToDisplayString() == symbol));
                    if (publicTypes.Length != 1 || (!ordinaryName && !operationPair && !migrationName))
                        Add("LAY002", "Public type requires its own matching file, except the exact command/handler operation pair", 6);
                }
                if (isApplication && request is not null)
                {
                    if (type.Name.EndsWith("Query", StringComparison.Ordinal) && !type.AllInterfaces.Any(i => i.Name == "ICachableRequest" && i.ContainingNamespace.ToDisplayString() == "LS.Application.Contracts.Interfaces.Common"))
                        Add("CACHE001", "Query must declare ICachableRequest with an explicit bypass/TTL/scope policy", 5);
                    if (type.Name.EndsWith("Command", StringComparison.Ordinal) && !type.AllInterfaces.Any(i => i.Name == "ICacheInvalidatorRequest" && i.ContainingNamespace.ToDisplayString() == "LS.Application.Contracts.Interfaces.Common"))
                        Add("CACHE002", "Command needs an explicit cache-impact decision; affected reads require ICacheInvalidatorRequest", 5);
                }
            }
            foreach (var creation in root.DescendantNodes().OfType<BaseObjectCreationExpressionSyntax>())
            {
                if (model.GetTypeInfo(creation).Type is not INamedTypeSymbol created || !Is(created, "LS.SharedKernel.Dtos.Common", "AppResponse")) continue;
                var assignments = creation.Initializer?.Expressions.OfType<AssignmentExpressionSyntax>().ToArray() ?? [];
                if (assignments.Any(a => a.Left.ToString() == "IsSuccess" && a.Right.IsKind(SyntaxKind.FalseLiteralExpression)) &&
                    !assignments.Any(a => a.Left.ToString() == "Error" && !a.Right.IsKind(SyntaxKind.NullLiteralExpression)))
                {
                    var enclosing = model.GetEnclosingSymbol(creation.SpanStart)?.ToDisplayString() ?? tree.FilePath;
                    findings.Add(new("ERR001", tree.FilePath, enclosing, creation.GetLocation().GetLineSpan().StartLinePosition.Line + 1,
                        "Failure initializer lacks a typed Error: " + creation.WithoutTrivia().NormalizeWhitespace().ToFullString(), 4));
                }
            }
        }
        return findings.DistinctBy(f => f.Identity).OrderBy(f => f.Identity, StringComparer.Ordinal).ToArray();
    }

    private static bool Is(INamedTypeSymbol type, string ns, string name) => type.Name == name && type.ContainingNamespace.ToDisplayString() == ns;
    private static IEnumerable<INamedTypeSymbol> BaseTypes(INamedTypeSymbol type)
    {
        for (INamedTypeSymbol? current = type; current is not null; current = current.BaseType) yield return current;
    }
}
